# -*- coding: utf-8 -*-
# Generated by Django 1.11.11 on 2018-04-10 17:04
from __future__ import unicode_literals

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('clients', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='client',
            name='date_added',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
